baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'kuraage'
theme = "shibui"

[params]
  author = "Mar"
  email = "your.email@example.com"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
